### PR TITLE
feat: Trakt Charts

### PR DESCRIPTION
**Pull request by brettpetch**
Adds Trakt.tv Popular and Trending lists with a valid API key.

Addresses part of #19.

### CODE REVIEW

**Comment by brettpetch** [comment]
https://github.com/ghomasHudson/Jellyfin-Auto-Collections/issues/19

**Comment by ghomasHudson** [comment]
Thanks for adding this (sorry it took me so long to get back to you).

Is there a reason why this needs a sqlite3 database?

**Comment by brettpetch** [comment]
Speeds up queries and caches the jf ids. I find that with large libraries that it is quite slow to search. Should likely add sqlite across the project as Jellyfin’s search isn’t really the fastest. On Jan 24, 2024, at 4:33 AM, Thomas Hudson ***@***.***> wrote:﻿
Thanks for adding this (sorry it took me so long to get back to you).
Is there a reason why this needs a sqlite3 database?

**Comment by BoHoliday** [comment]
This doesn't seem to be removing items, just adding. Is there something I need to modify?

**Comment by ghomasHudson** [comment]
A recent pull request to dockerize things means the config file stuff has changed.

**Comment by HellBoyJr** [comment]
Any prediction?

**Comment by ghomasHudson** [comment]
> Any prediction?

See #19

**Comment by ghomasHudson** [comment]
The repo has diverged quite a bit from when this pull request was made so I'll abandon it here. Thanks for the code, it was a good reference when implementing trakt intergration.

**Pull request closed without merging**
